//import org.jetbrains.kotlin.incremental.BuildInfo
import java.time.Instant.now
import walkie.talkie.git.*

plugins {
    alias(libs.plugins.android.application)
    /* id("com.android.library") */
    alias(libs.plugins.jetbrains.kotlin.android)
    alias(libs.plugins.compose.compiler)
    kotlin("plugin.serialization")
}

tasks.register("generateBuildInfo") {
    doLast {
        val commit = gitCommit()
        val branch = gitBranch()
        val repo = gitRemote()

        val outputDir = layout.buildDirectory.dir("generated/source/buildInfo/walkie/talkie")
        val file = outputDir.get().file("BuildInfo.kt").asFile
        file.parentFile.mkdirs()

        println("WRITE To: $file")

        file.writeText(
            """
            package walkie.talkie                
            object BuildInfo {
                const val COMMIT = "$commit"
                const val BRANCH = "$branch"
                const val REPO = "$repo"
            }
        """.trimIndent()
        )

        //println("commit: $commit $BuildInfo")
    }
}

tasks.named("preBuild") {
    dependsOn("generateBuildInfo")
}

android {
    val baseName = "Walkie Talkie"

    namespace = "walkie.talkie"
    compileSdk = 36

    buildFeatures {
        buildConfig = true
    }

    defaultConfig {
        applicationId = "walky.talky"
        minSdk = 30
        targetSdk = 36
        versionCode = 4
        versionName = "0.0.4"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary = true
        }
        buildConfigField("long", "BUILD_TIME", now().toEpochMilli().toString())
        manifestPlaceholders["baseName"] = baseName
    }

    buildFeatures {
       compose = true
    }

    buildTypes {
        release {
            /* Keep these off until fixing all the name clashes generated by minifying/obfuscating process. Investigate the @Keep annotation */
            isMinifyEnabled = true
            isShrinkResources = true
            signingConfig = signingConfigs.getByName("debug")
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )

            versionNameSuffix = ""
            manifestPlaceholders["appType"] = versionNameSuffix!!
        }
        debug {
            /* applicationIdSuffix = ".debug" */
            versionNameSuffix = "(debug)"

            manifestPlaceholders["appType"] = "." + versionNameSuffix!!

            isMinifyEnabled = false
            isShrinkResources = false
            isDebuggable = true
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    buildFeatures {
        compose = true
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.1"
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
    flavorDimensions += listOf("R")
    productFlavors {
        create("devel") {
            dimension = "R"
            versionNameSuffix = "(devel)"
            applicationIdSuffix = ".devel"

            manifestPlaceholders["appFlavour"] = "." + versionNameSuffix!!
        }
        create("alpha") {
            dimension = "R"
            versionNameSuffix = "(alpha)"
            manifestPlaceholders["appFlavour"] = "." + versionNameSuffix!!
        }
        create("beta") {
            dimension = "R"
            versionNameSuffix = "(beta)"
            manifestPlaceholders["appFlavour"] = "." + versionNameSuffix!!

        }
        create("ship") {
            dimension = "R"
            versionNameSuffix = ""
            manifestPlaceholders["appFlavour"] = versionNameSuffix!!
        }

        create("custom") {
            dimension = "R"
            versionNameSuffix = "(custom)"
            applicationIdSuffix = ".custom"
            manifestPlaceholders["appFlavour"] = "." + versionNameSuffix!!
        }
    }

    sourceSets {
        getByName("main") {
            java.srcDir(layout.buildDirectory.dir("generated/source/buildInfo/walkie/talkie"))
        }
    }
    buildToolsVersion = "36.0.0"
}

kotlin {
    jvmToolchain(17)
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.kotlin.reflect)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.activity.ktx)
    implementation(libs.androidx.navigation.runtime.ktx)
    implementation(libs.androidx.navigation.compose)
    implementation(libs.androidx.constraintlayout.compose.v101)
    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.ui.test.junit4)
    debugImplementation(libs.androidx.ui.tooling)
    debugImplementation(libs.androidx.ui.test.manifest)
    implementation(libs.kotlinx.serialization.json)
    implementation (libs.androidx.core.splashscreen)
    implementation(libs.androidx.compose.material.icons.extended)
    /* implementation(libs.androidx.multidex) */

    implementation(project(":glue_inc"))
    implementation(project(":glue"))
    implementation(project(":comm"))
    implementation(project(":chat"))
    implementation(project(":wifidirect"))
    implementation(project(":util"))
}
